matches:
  - trigger: ";;co"
    replace: "copilot --banner"
  - trigger: ";;aw"
    replace: "activate @.github/prompts/create-agentic-workflow.prompt.md"
  - trigger: ";;dn"
    replace: "أريد تقريرًا إخباريًا يوميًا عن النشاط في هذا المستودع."
  - trigger: ";;pr"
    replace: "طلبات السحب والمشاكل وبعض الرؤى حول كيفية سير المشروع"
  - trigger: ";;sc"
    replace: "الساعة 8 صباحًا بتوقيت المحيط الهادئ، وقرر لي آخر التفاصيل"
